---
- name: add zabbix.com key
  apt_key: url=http://repo.zabbix.com/zabbix-official-repo.key state=present

- name: add zabbix.com repo
  apt_repository: repo='deb http://repo.zabbix.com/zabbix/3.4/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} main contrib non-free' state=present

- name: Update apt cache
  apt: update_cache=yes

- name: Install related packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-agent

- name: Copy over our modified config file
  template:
    src: zabbix_agentd.conf
    dest: "/etc/zabbix/zabbix_agentd.conf"

- name: Open Firewall for zabbix checks
  ufw:
    rule: allow
    port: 10050:10051
    proto: tcp

- name: Enable agent
  service: 
    name: zabbix-agent.service
    enabled: yes
  notify: restart zabbix-agent

