---
- name: "Install and start"
  block:
    - name: Install Zabbix Agent2
      include_tasks: present.yml

    - name: Install defined addons
      include_tasks: "addons/{{addon}}.yml"
      loop: "{{zabbix_addons}}"
      loop_control:
        loop_var: addon # set loop_var to avoid ansible complaining about inner variable
      when: zabbix_addons is defined

    - name: "Start Zabbix Agent2 service"
      service:
        name:    "zabbix-agent2"
        enabled: "yes"
        state:   "restarted"

  when: zabbix_uninstall is not defined or zabbix_uninstall == 0

# no playbook actually sets zabbix_uninstall, but good to have the option for manual uninstallation via command line
- name: "Remove Agent"
  block:
    - name: Install Zabbix Agent2
      include_tasks: absent.yml

  when: zabbix_uninstall is defined and zabbix_uninstall == "1"
...
