---
- name: Create keyrings directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: 'Add Zabbix public key'
  ansible.builtin.get_url:
    url:  '{{ zabbix_repo.url }}/zabbix-official-repo.key'
    dest: '/etc/apt/keyrings/zabbix.asc'
    mode: '0644'

- name: 'Add Zabbix apt repository'
  ansible.builtin.apt_repository:
    filename: 'zabbix.list'
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/zabbix.asc] {{ zabbix_repo.url }}/{{ zabbix_repo.repo }} {{ ansible_distribution_release }} main"
    state: 'present'
    update_cache: 'yes'

- name: 'Install agent2'
  ansible.builtin.apt:
    name: 'zabbix-agent2'
    state: 'latest'
    update_cache: 'yes'

- name: "Open zabbix port in firewall"
  ufw:
    rule: "allow"
    port: "10050"
    from_ip:  "{{ zabbix_server_ip }}"

- name: "Update agent config"
  ini_file:
    path: "/etc/zabbix/zabbix_agent2.conf"
    section: null
    no_extra_spaces: yes
    option: "{{ item.key   }}"
    value:  "{{ item.value }}"
  with_items:
    - { key: "Server",       value: "{{ zabbix_server_hostname }}" }
    - { key: "ServerActive", value: "{{ zabbix_server_hostname }}" }
    - { key: "HostnameItem", value: "system.hostname" }
    - { key: "HostMetadataItem", value: "system.hostname" }
    - { key: "Timeout", value: 30 }
    #- { key: "Include", value: "/etc/zabbix/zabbix_agent2.d/*.conf" }
    - { key: "UnsafeUserParameters", value: 1}
    - { key: "LogFileSize", value: 5}

- name: "Remove Hostname from config (to use auto-generated one)"
  ini_file:
    path: "/etc/zabbix/zabbix_agent2.conf"
    section: null
    no_extra_spaces: yes
    option: "Hostname"
    state: absent
    allow_no_value: yes
...
