---
- name: Install SMARTmontools
  apt:
    name: smartmontools
    state: present
    update_cache: yes

# Allow the Zabbix account to run smartctl as sudo
- name: Copy zabbix smartctl sudoers.d file
  ansible.builtin.copy:
    src: "files/addons/smart/{{item}}"
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: '0640'
  loop:
    - zabbix-smartctl

# Copy over the scripts to /etc/zabbix/scripts
- name: Copy scripts
  ansible.builtin.copy:
    src: "files/addons/smart/{{item}}"
    dest: /etc/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: '0744'
  loop:
    - smartctl-storage-discovery.sh
    - smartctl-tofile.sh
    
# Copy over the zabbix config files
- name: Copy SMART zabbix config
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/etc/zabbix/zabbix_agent2.d/"
    owner: zabbix
    group: zabbix
    mode: '0744'
  loop:
    - files/addons/smart/smartctl.conf

#todo: maybe combine the 3 above loops to iterate over hashtable instead

# Add cron entry to run smartctl-tofile.sh every 30 minutes
- name: Create smartctl-tofile cron file under /etc/cron.d
  ansible.builtin.cron:
    name: smartctl-tofile
    weekday: "*"
    minute: "*/30"
    hour: "*"
    user: root
    job: "/etc/zabbix/scripts/smartctl-tofile.sh"
    cron_file: smartctl-tofile
...
